### ISSUE TITLE
Background is gone

### ISSUE THREAD

**Issue by skulane** [Emielvr/ti2206-space-invaders#57]
The background on the startscreen is gone!
<bug

**Comment by vwigmore** [comment]
![](http://i.imgur.com/mJfCvB5.png)

**Comment by codesalad** [comment]
Should be: C:\Users\wnguyen\spaceinvaders\target\classes\gui\view\Mainview.fxml

Note that you're missing \gui\ in the URL.

**Comment by vwigmore** [comment]
@codesalad 
the whole resources folder has a duplicate ( src/resources and src/main/java/gui/resources ) and the launcher is pointing to the duplicated folder with the older versions of the views

**Comment by codesalad** [comment]
Background bug fixed by Viktor a42b75031bd49d23810046383bd17497c435b4f1
